### ISSUE TITLE
backend.py doesn't compile with Python 2.4.3

### ISSUE THREAD

**Issue by haydnhuntley** [dnephin/TracAdvancedSearchPlugin#12]
byte-compiling build/bdist.linux-x86_64/egg/tracadvsearch/backend.py to backend.pyc
  File "build/bdist.linux-x86_64/egg/tracadvsearch/backend.py", line 80
    q_string = " AND ".join(q_parts) if q_parts else '_:_'

I tried rewriting that line of code as:

```
    if q_parts:
        q_string = " AND ".join(q_parts)
    else:
        q_string = '*:*'
```

But now it fails to compile on the next line:

byte-compiling build/bdist.linux-x86_64/egg/tracadvsearch/backend.py to backend.pyc
  File "build/bdist.linux-x86_64/egg/tracadvsearch/backend.py", line 85
    try:
    ^

Does this code require a newer version of Python to work?

**Comment by dnephin** [comment]
Yes, this plugin was written for Python 2.5+

**Comment by haydnhuntley** [comment]
Thank you for replying.
I tried to update the "X if bool else Y" statements, but that wasn't 
enough to make it compile.
We'll update to a newer version of Python soon, and then we'll be able 
to use your plugin.

--Haydn

dnephin wrote:

> Yes, this plugin was written for Python 2.5+

## 

Haydn Huntley                           office: 808-573-9522
haydn.huntley@gmail.com                   home: 808-575-2571
                                          cell: 808-283-5173

**Comment by ChauChicken** [comment]
Generated pull request https://github.com/dnephin/TracAdvancedSearchPlugin/pull/13
