### ISSUE TITLE
To be able to install from PyPI

### ISSUE THREAD

**Issue by t2y** [dnephin/TracAdvancedSearchPlugin#15]
Hi,

Installing TracAdvancedSearchPlugin using pip/easy_install command from PyPI is convenient for users and developers. By Python packaging makes the plugin more distributable.

http://pypi.python.org/pypi/

**Comment by t2y** [comment]
If #16 will be completed, you can upload the package into PyPI.

http://docs.python.org/2/distutils/uploading.html

**Comment by dnephin** [comment]
Done in #16
